// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSyncRule(arg1) {
  return window['go']['app']['App']['AddSyncRule'](arg1);
}

export function CheckRemoteSyncDeps(arg1) {
  return window['go']['app']['App']['CheckRemoteSyncDeps'](arg1);
}

export function ClearDebugLog() {
  return window['go']['app']['App']['ClearDebugLog']();
}

export function CloseTerminalSession(arg1) {
  return window['go']['app']['App']['CloseTerminalSession'](arg1);
}

export function ConnectSSH(arg1) {
  return window['go']['app']['App']['ConnectSSH'](arg1);
}

export function CopyLocalDirectory(arg1, arg2) {
  return window['go']['app']['App']['CopyLocalDirectory'](arg1, arg2);
}

export function CopyLocalFile(arg1, arg2) {
  return window['go']['app']['App']['CopyLocalFile'](arg1, arg2);
}

export function CreateLocalDirectory(arg1) {
  return window['go']['app']['App']['CreateLocalDirectory'](arg1);
}

export function CreateLocalFile(arg1) {
  return window['go']['app']['App']['CreateLocalFile'](arg1);
}

export function CreateLocalTerminalSession() {
  return window['go']['app']['App']['CreateLocalTerminalSession']();
}

export function CreatePTY(arg1) {
  return window['go']['app']['App']['CreatePTY'](arg1);
}

export function DeleteLocalDirectory(arg1) {
  return window['go']['app']['App']['DeleteLocalDirectory'](arg1);
}

export function DeleteLocalFile(arg1) {
  return window['go']['app']['App']['DeleteLocalFile'](arg1);
}

export function DeleteRemoteDirectory(arg1, arg2) {
  return window['go']['app']['App']['DeleteRemoteDirectory'](arg1, arg2);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['app']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DisconnectSSH(arg1) {
  return window['go']['app']['App']['DisconnectSSH'](arg1);
}

export function DownloadDirectory(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadDirectory'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['app']['App']['ExecuteCommand'](arg1, arg2);
}

export function GetCurrentDirectory(arg1) {
  return window['go']['app']['App']['GetCurrentDirectory'](arg1);
}

export function GetDebugLogPath() {
  return window['go']['app']['App']['GetDebugLogPath']();
}

export function GetDefaultEditorDirectory() {
  return window['go']['app']['App']['GetDefaultEditorDirectory']();
}

export function GetFileClipboard() {
  return window['go']['app']['App']['GetFileClipboard']();
}

export function GetHomeDirectory() {
  return window['go']['app']['App']['GetHomeDirectory']();
}

export function GetNextUntitledFileName(arg1) {
  return window['go']['app']['App']['GetNextUntitledFileName'](arg1);
}

export function GetOpenEditorCount() {
  return window['go']['app']['App']['GetOpenEditorCount']();
}

export function GetParentDirectory(arg1) {
  return window['go']['app']['App']['GetParentDirectory'](arg1);
}

export function GetRemoteHomeDir(arg1) {
  return window['go']['app']['App']['GetRemoteHomeDir'](arg1);
}

export function GetSSHConfig() {
  return window['go']['app']['App']['GetSSHConfig']();
}

export function GetSyncRules() {
  return window['go']['app']['App']['GetSyncRules']();
}

export function GetTerminalSettings() {
  return window['go']['app']['App']['GetTerminalSettings']();
}

export function IsDirectory(arg1) {
  return window['go']['app']['App']['IsDirectory'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['app']['App']['ListFiles'](arg1, arg2);
}

export function ListLocalFiles(arg1) {
  return window['go']['app']['App']['ListLocalFiles'](arg1);
}

export function MoveLocalFile(arg1, arg2) {
  return window['go']['app']['App']['MoveLocalFile'](arg1, arg2);
}

export function OpenEditorWindow(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenEditorWindow'](arg1, arg2, arg3);
}

export function OpenFileBrowserWindow(arg1) {
  return window['go']['app']['App']['OpenFileBrowserWindow'](arg1);
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function OpenTerminalAtPath(arg1) {
  return window['go']['app']['App']['OpenTerminalAtPath'](arg1);
}

export function PasteFiles(arg1) {
  return window['go']['app']['App']['PasteFiles'](arg1);
}

export function ReadLocalFile(arg1) {
  return window['go']['app']['App']['ReadLocalFile'](arg1);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['app']['App']['ReadRemoteFile'](arg1, arg2);
}

export function RemoveSyncRule(arg1) {
  return window['go']['app']['App']['RemoveSyncRule'](arg1);
}

export function RenameLocalFile(arg1, arg2) {
  return window['go']['app']['App']['RenameLocalFile'](arg1, arg2);
}

export function RenameRemoteFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameRemoteFile'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetFileClipboard(arg1, arg2) {
  return window['go']['app']['App']['SetFileClipboard'](arg1, arg2);
}

export function SetSyncSource(arg1, arg2) {
  return window['go']['app']['App']['SetSyncSource'](arg1, arg2);
}

export function SetTerminalSettings(arg1) {
  return window['go']['app']['App']['SetTerminalSettings'](arg1);
}

export function ShowAllEditorWindows() {
  return window['go']['app']['App']['ShowAllEditorWindows']();
}

export function StartEditorServer() {
  return window['go']['app']['App']['StartEditorServer']();
}

export function StartLocalTerminalSession(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StartLocalTerminalSession'](arg1, arg2, arg3, arg4);
}

export function StartSync(arg1) {
  return window['go']['app']['App']['StartSync'](arg1);
}

export function StartTerminalSession(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartTerminalSession'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopSync(arg1) {
  return window['go']['app']['App']['StopSync'](arg1);
}

export function UpdateSyncRule(arg1) {
  return window['go']['app']['App']['UpdateSyncRule'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2, arg3);
}

export function WriteDebugLog(arg1) {
  return window['go']['app']['App']['WriteDebugLog'](arg1);
}

export function WriteLocalFile(arg1, arg2) {
  return window['go']['app']['App']['WriteLocalFile'](arg1, arg2);
}

export function WriteRemoteFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteRemoteFile'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['app']['App']['WriteToTerminal'](arg1, arg2);
}
