// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function AddSyncRule(arg1:app.SyncRule):Promise<app.SyncRule>;

export function CheckRemoteSyncDeps(arg1:string):Promise<app.RemoteDepsStatus>;

export function ClearDebugLog():Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:app.SSHConfigEntry):Promise<string>;

export function CopyFilesToSystemClipboard(arg1:Array<string>):Promise<void>;

export function CopyLocalDirectory(arg1:string,arg2:string):Promise<void>;

export function CopyLocalFile(arg1:string,arg2:string):Promise<void>;

export function CopyRemoteFilesToSystemClipboard(arg1:string,arg2:Array<string>):Promise<void>;

export function CreateLocalDirectory(arg1:string):Promise<void>;

export function CreateLocalFile(arg1:string):Promise<void>;

export function CreateLocalTerminalSession():Promise<string>;

export function CreatePTY(arg1:string):Promise<void>;

export function DeleteLocalDirectory(arg1:string):Promise<void>;

export function DeleteLocalFile(arg1:string):Promise<void>;

export function DeleteRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function GetCurrentDirectory(arg1:string):Promise<string>;

export function GetDebugLogPath():Promise<string>;

export function GetDefaultEditorDirectory():Promise<string>;

export function GetFileClipboard():Promise<app.ClipboardData>;

export function GetHomeDirectory():Promise<string>;

export function GetNextUntitledFileName(arg1:string):Promise<string>;

export function GetOpenEditorCount():Promise<number>;

export function GetParentDirectory(arg1:string):Promise<string>;

export function GetRemoteHomeDir(arg1:string):Promise<string>;

export function GetSSHConfig():Promise<Array<app.SSHConfigEntry>>;

export function GetSyncRules():Promise<Array<app.SyncRule>>;

export function GetTerminalSettings():Promise<string>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<app.FileInfo>>;

export function ListLocalFiles(arg1:string):Promise<Array<app.LocalFileInfo>>;

export function LoadEditorTabs():Promise<string>;

export function LoadFilesTabs():Promise<string>;

export function LoadTerminalSessions():Promise<string>;

export function MoveLocalFile(arg1:string,arg2:string):Promise<void>;

export function OpenEditorWindow(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function OpenFileBrowserWindow(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenTerminalAtPath(arg1:string):Promise<void>;

export function PasteFiles(arg1:string):Promise<void>;

export function ReadLocalFile(arg1:string):Promise<string>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function RemoveSyncRule(arg1:string):Promise<void>;

export function RenameLocalFile(arg1:string,arg2:string):Promise<void>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveEditorTabs(arg1:string):Promise<void>;

export function SaveFilesTabs(arg1:string):Promise<void>;

export function SaveTerminalSessions(arg1:string):Promise<void>;

export function SetFileClipboard(arg1:Array<string>,arg2:string):Promise<void>;

export function SetSyncSource(arg1:string,arg2:string):Promise<void>;

export function SetTerminalSettings(arg1:string):Promise<void>;

export function ShowAllEditorWindows():Promise<void>;

export function StartEditorServer():Promise<void>;

export function StartLocalTerminalSession(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function StartSync(arg1:string):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopSync(arg1:string):Promise<void>;

export function TestSyncConnection(arg1:string):Promise<void>;

export function UpdateSyncRule(arg1:app.SyncRule):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WriteDebugLog(arg1:string):Promise<void>;

export function WriteLocalFile(arg1:string,arg2:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
