// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function ClearDebugLog():Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:app.SSHConfigEntry):Promise<string>;

export function CreateLocalFile(arg1:string):Promise<void>;

export function CreateLocalTerminalSession():Promise<string>;

export function CreatePTY(arg1:string):Promise<void>;

export function DeleteLocalDirectory(arg1:string):Promise<void>;

export function DeleteLocalFile(arg1:string):Promise<void>;

export function DeleteRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function GetCurrentDirectory(arg1:string):Promise<string>;

export function GetDefaultEditorDirectory():Promise<string>;

export function GetHomeDirectory():Promise<string>;

export function GetNextUntitledFileName(arg1:string):Promise<string>;

export function GetOpenEditorCount():Promise<number>;

export function GetRemoteHomeDir(arg1:string):Promise<string>;

export function GetSSHConfig():Promise<Array<app.SSHConfigEntry>>;

export function GetTerminalSettings():Promise<string>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<app.FileInfo>>;

export function ListLocalFiles(arg1:string):Promise<Array<app.LocalFileInfo>>;

export function OpenEditorWindow(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function ReadLocalFile(arg1:string):Promise<string>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetTerminalSettings(arg1:string):Promise<void>;

export function ShowAllEditorWindows():Promise<void>;

export function StartEditorServer():Promise<void>;

export function StartLocalTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WriteDebugLog(arg1:string):Promise<void>;

export function WriteLocalFile(arg1:string,arg2:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
