// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function CreatePTY(arg1) {
  return window['go']['main']['App']['CreatePTY'](arg1);
}

export function DeleteLocalDirectory(arg1) {
  return window['go']['main']['App']['DeleteLocalDirectory'](arg1);
}

export function DeleteLocalFile(arg1) {
  return window['go']['main']['App']['DeleteLocalFile'](arg1);
}

export function DeleteRemoteDirectory(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteDirectory'](arg1, arg2);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DownloadDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadDirectory'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function GetCurrentDirectory(arg1) {
  return window['go']['main']['App']['GetCurrentDirectory'](arg1);
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetRemoteHomeDir(arg1) {
  return window['go']['main']['App']['GetRemoteHomeDir'](arg1);
}

export function GetSSHConfig() {
  return window['go']['main']['App']['GetSSHConfig']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListLocalFiles(arg1) {
  return window['go']['main']['App']['ListLocalFiles'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function StartTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminalSession'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
