// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:main.SSHConfigEntry):Promise<string>;

export function CreatePTY(arg1:string):Promise<void>;

export function DeleteLocalDirectory(arg1:string):Promise<void>;

export function DeleteLocalFile(arg1:string):Promise<void>;

export function DeleteRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function GetCurrentDirectory(arg1:string):Promise<string>;

export function GetHomeDirectory():Promise<string>;

export function GetRemoteHomeDir(arg1:string):Promise<string>;

export function GetSSHConfig():Promise<Array<main.SSHConfigEntry>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function ListLocalFiles(arg1:string):Promise<Array<main.LocalFileInfo>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
